sudo: false
language: c
script: make -C binutils test APPNAME=$(printf '\xF0\x9F\x8C\x88')
matrix:
  include:
    - compiler: gcc
      rvm: 1.8.7

    - addons:
        apt:
          packages: gcc-multilib
      compiler: gcc
      env: CFLAGS="-m32" LDFLAGS="-m32"
      rvm: 1.9.3

    - compiler: clang
      rvm: 2.0.0

    - addons:
        apt:
          packages: gcc-multilib
      compiler: clang
      env: CFLAGS="-m32" LDFLAGS="-m32"
      rvm: 2.1.1

    - before_script: export LANG=en_US.UTF-8
      language: objective-c
      compiler: clang
      rvm: system

    - before_script: export LANG=en_US.UTF-8
      language: objective-c
      compiler: clang
      env: CFLAGS="-m32" LDFLAGS="-m32"
