RAKE = ruby vendor/mruby/minirake

all :
	$(RAKE)
.PHONY : all

clean :
	$(RAKE) clean
.PHONY : clean

clean_all :
	$(RAKE) clean_all
.PHONY : clean_all

install :
	$(RAKE) install
.PHONY : install

uninstall :
	$(RAKE) uninstall
.PHONY : uninstall

test :
	$(RAKE) test
.PHONY : test
